### ISSUE TITLE
asrock b365itx + i5 9600k + Rx5700 点亮

### ISSUE THREAD

**Issue by JackMelfi** [Good0007/B365ITX-Hackintosh-OC#1]
首先感谢作者的分享！

硬件除了cpu跟显卡跟此repo都相同，尝试直接用此efi引导会卡在启动引导阶段，verbose都不走， 因为配置文件关了开机菜单而且通常默认选中的都会是OpenCode所在的EFI而不是MacOS
爬贴尝试了一下目前修改一些配置可以成功进入系统

**镜像：**
 黑果小兵 10.15.1 安装完成后手动升级10.15.2 beta（不插显卡，smbios型号使用了Macmini8,1）
**config.plist ：**
插显卡，重启使用OC引导，配置
- Boot—MmioWhitelist
  - 第二项开启（因为我的主板会卡在IOPCIFamily这里，可能跟这里有关系，或许不开也行）
  
- Misc—–Boot: 
  - HideSelf: 选择true
  - ShowPicker: 选择true
  - Timeout: 选择4(秒)
  - UsePicker: 使用true

- latformInfo—–Generic：
  - SystemProductName： MacPro7,1
  - 其他用clover configurator生成

- Kernel—–Add
  - WhatEverGreen enable 配置成false ，否进系统会黑屏,因为还不兼容Rx5700

其他保持不变。
听说10.15.1正式版也能驱动Rx5700，不过有花屏， 但是我没试过

因为我没装win，开机默认选的是mac，这样能进系统，但是鼠标键盘没反应，不知道是否要加第三方键盘驱动之类的，准备晚些时候再爬贴。

目前我有有一些没解决的问题：

1. 如果有如何驱动键鼠方面的建议的话，可否方便提示下？
2. B365芯片组是2代的马甲，有可能原生支持NVRAM，但是我不知道如何排除OC跟Clover的影响去测试是否支持原生NVRAM

**Comment by Good0007** [comment]
你BOIS版本多少呢，BOIS应该是要设置下 XHCI Hand-off, Enabled 。另外5700xt都是完美的，考虑可以刷下5700xt的BOIS吧，这个B365I是不支持原生nvram的 我已经测过了，如果你和我的型号一致键鼠驱动应该都是可以的呀，如果不行的话就使用usbinjectAll先驱动起来，然后进系统定制usbports，oc在开机菜单这块还没完善，配置起来也复杂，所以我现在换回clover，等oc过段时间在上，有空我补上clover的配置

**Comment by JackMelfi** [comment]
我看了下Bios版本是B365M-ITX/ac p4.20， xhci hand-off已经开启了的。但是不行，我试试用usbinject
All

**Comment by Good0007** [comment]
对了，你的机型必用imac19,1 不然硬解或者usb肯定不行的！我这个是针对这个机型定制的

**Comment by JackMelfi** [comment]
ok了，换imac19,1 OK了。Rx5700黑屏是WhatEverGreen的原因，跟机型无关，我之前改错了。
