### ISSUE TITLE
大佬 ，DW1820A需要转接卡吗 ？

### ISSUE THREAD

**Issue by shen-lan** [Good0007/B365ITX-Hackintosh-OC#11]
华擎B365mITX只有一个m2口  没有额外的  pcie口呀。拆机网卡好像就是m2口的吧

**Comment by shen-lan** [comment]
DW1820A 有购买地址么

**Comment by Good0007** [comment]
> DW1820A 有购买地址么
1820a不用转接，原来网卡拆掉就可以安装，某宝、咸鱼都可以买。可以看我博客有图

**Comment by shen-lan** [comment]
> 手头笔记本有一片拆机卡94360cs2,拆掉1820a换上cs2,以为一切完美大功告成 
我看了您博客的图    94360cs2安装的时候似乎用了转接卡？ 如果采用该网卡 还需要网卡驱动相关设置吗

**Comment by Good0007** [comment]
94360cs2是需要转接板的，efi里默认带了1820a驱动，如果用cs2 要手动删了1820a的驱动

**Comment by shen-lan** [comment]
多谢大佬热心回答。
