### ISSUE TITLE
图形化界面无法生效

### ISSUE THREAD

**Issue by zuo000** [Good0007/B365ITX-Hackintosh-OC#20]
怎么设置都是命令行引导界面,是不是openCanopy.efi驱动有问题?

**Comment by zuo000** [comment]
换了0.6.3的opencanopy驱动好了，感觉楼主驱动不配套

**Comment by Good0007** [comment]
> 换了0.6.3的opencanopy驱动好了，感觉楼主驱动不配套

好 多谢反馈

**Comment by zuo000** [comment]
> > 换了0.6.3的opencanopy驱动好了，感觉楼主驱动不配套
> 
> 好 多谢反馈

^_^
