### ISSUE TITLE
相同的主板，替换EFI后，无法进入系统

### ISSUE THREAD

**Issue by superleeyom** [Good0007/B365ITX-Hackintosh-OC#23]
我一直用的是大佬维护的EFI，非常感谢，最近看到你更新了最新的oc版本，准备替换一下，我的配置如下：

- cpu：intel i5 9400 散片
- 主板：华擎B365M-ITX/AC 
- 显卡：盈通 rx580 4g 2304sp 
- 硬盘：海康威视 C2000 pro 256g SSD 
- 内存条：宇瞻 DDR4 2666 16g*2 
- 散热器：ID-COOLING IS-40X 
- 电源：海盗船 sf450 金牌
- 无线网卡：BCM94360CS2 无线网卡+转接卡
- 目前系统版本：macOS 11.1

按照提示，我选择的是「核显+独显配置」的配置，同时删除了1820A驱动kext，并对oc配置做了如下的操作：
![image](https://user-images.githubusercontent.com/22115219/115943562-3645af00-a4e3-11eb-88dc-26054a356d40.png)
最终只保留了如下的驱动：
![image](https://user-images.githubusercontent.com/22115219/115943597-6ab96b00-a4e3-11eb-8744-db106db4e835.png)
文中提到：**由于新版本bootstrap已被弃用，若更新后OC引导丢失，请进win|pe系统使用easyuefi或者bootice重新将引导定位至:EFI\BOOT\BOOTx64.efi**，我在pe系统里，使用easyuefi，对oc引导修改成`EFI\BOOT\BOOTx64.efi`后，发现进不去系统，系统界面提示如下：
![image](https://user-images.githubusercontent.com/22115219/115943693-106cda00-a4e4-11eb-8d13-45be0eab800d.png)
另外我发现对oc引导修改成`EFI\BOOT\BOOTx64.efi`后并重启，发现重新又多了一个相同的 opencore的引导，这两个引导细节如下：
![image](https://user-images.githubusercontent.com/22115219/115943742-62156480-a4e4-11eb-943e-bf8a679fe347.png)
![image](https://user-images.githubusercontent.com/22115219/115943758-75283480-a4e4-11eb-88c1-87b30e6be856.png)
原先修改的，似乎又变回去了，哦，对了，我使用的 opencore configurator 的版本是 
![image](https://user-images.githubusercontent.com/22115219/115943884-1b743a00-a4e5-11eb-8389-128b7db94d21.png)
所以最后无奈，只能恢复原先的EFI，删除了其中指向`EFI\BOOT\BOOTx64.efi`的那个opencore的引导，最后附上我在您基础上修改的EFI配置：链接: https://pan.baidu.com/s/1pmHn5doAgxYMt5ajTljGJw 提取码: c2t2 
期待您的回复，感谢你对该EFI的维护！

**Comment by Good0007** [comment]
这个有点问题 我等会更新新版

**Comment by Good0007** [comment]
> 我一直用的是大佬维护的EFI，非常感谢，最近看到你更新了最新的oc版本，准备替换一下，我的配置如下：
> 
> * cpu：intel i5 9400 散片
> * 主板：华擎B365M-ITX/AC
> * 显卡：盈通 rx580 4g 2304sp
> * 硬盘：海康威视 C2000 pro 256g SSD
> * 内存条：宇瞻 DDR4 2666 16g*2
> * 散热器：ID-COOLING IS-40X
> * 电源：海盗船 sf450 金牌
> * 无线网卡：BCM94360CS2 无线网卡+转接卡
> * 目前系统版本：macOS 11.1
> 
> 按照提示，我选择的是「核显+独显配置」的配置，同时删除了1820A驱动kext，并对oc配置做了如下的操作：
> ![image](https://user-images.githubusercontent.com/22115219/115943562-3645af00-a4e3-11eb-88dc-26054a356d40.png)
> 最终只保留了如下的驱动：
> ![image](https://user-images.githubusercontent.com/22115219/115943597-6ab96b00-a4e3-11eb-8744-db106db4e835.png)
> 文中提到：**由于新版本bootstrap已被弃用，若更新后OC引导丢失，请进win|pe系统使用easyuefi或者bootice重新将引导定位至:EFI\BOOT\BOOTx64.efi**，我在pe系统里，使用easyuefi，对oc引导修改成`EFI\BOOT\BOOTx64.efi`后，发现进不去系统，系统界面提示如下：
> ![image](https://user-images.githubusercontent.com/22115219/115943693-106cda00-a4e4-11eb-8d13-45be0eab800d.png)
> 另外我发现对oc引导修改成`EFI\BOOT\BOOTx64.efi`后并重启，发现重新又多了一个相同的 opencore的引导，这两个引导细节如下：
> ![image](https://user-images.githubusercontent.com/22115219/115943742-62156480-a4e4-11eb-943e-bf8a679fe347.png)
> ![image](https://user-images.githubusercontent.com/22115219/115943758-75283480-a4e4-11eb-88c1-87b30e6be856.png)
> 原先修改的，似乎又变回去了，哦，对了，我使用的 opencore configurator 的版本是
> ![image](https://user-images.githubusercontent.com/22115219/115943884-1b743a00-a4e5-11eb-8389-128b7db94d21.png)
> 所以最后无奈，只能恢复原先的EFI，删除了其中指向`EFI\BOOT\BOOTx64.efi`的那个opencore的引导，最后附上我在您基础上修改的EFI配置：链接: https://pan.baidu.com/s/1pmHn5doAgxYMt5ajTljGJw 提取码: c2t2
> 期待您的回复，感谢你对该EFI的维护！

我没有b365itx了，只能找群友测试，可能测的不够全面。已更新最新版，可以试试，如果还有问题可以加我好友交流

**Comment by superleeyom** [comment]
感谢，已替换成功，目前已升级成功到最新的系统版本，请教个问题，就是 Hackintool工具检测到的引导工具为啥还是 0.6.3呢？
![image](https://user-images.githubusercontent.com/22115219/115957691-7aae6a80-a536-11eb-9d10-0e1465ca6053.png)

**Comment by Good0007** [comment]
> 感谢，已替换成功，目前已升级成功到最新的系统版本，请教个问题，就是 Hackintool工具检测到的引导工具为啥还是 0.6.3呢？
> ![image](https://user-images.githubusercontent.com/22115219/115957691-7aae6a80-a536-11eb-9d10-0e1465ca6053.png)

引导界面选择rest nvram 清空nvram ，下次进去就可以了。如果清空nvram引导丢失 再用bootice修复引导就好了

**Comment by superleeyom** [comment]
@Good0007 好的，感谢！！！
