### ISSUE TITLE
华擎b365m itx/ac主板使用此配置开机过程中断电重启

### ISSUE THREAD

**Issue by imzhengziyi** [Good0007/B365ITX-Hackintosh-OC#7]
华擎b365m itx/ac主板使用此OC 配置开机过程中会自动断电重启，重启可以开机，电脑提示开机过程中遇到问题。每次开机都是一样的情况，必须自动断电重启才能进入系统！

**Comment by Good0007** [comment]
你是dw1820网卡么？开机应该提示电脑出现问题吧 ，复制下内核崩溃日志发来看看

**Comment by imzhengziyi** [comment]
感谢您的回复：

我是原机网卡还没有更换1820a，不打算更换1820a的，是不是因为网卡原因导致的这个问题呢，如果是，是否可以删除网卡驱动解决呢！

我目前是使用clover了

左手代码右手诗 <notifications@github.com> 于2020年3月13日周五 下午12:48写道：

**Comment by Good0007** [comment]
应该是，删除网卡驱动就好了
