### ISSUE TITLE
OC怎么用？直接覆盖efi?

### ISSUE THREAD

**Issue by naughtyGitCat** [Good0007/B365ITX-Hackintosh-OC#8]
同型号主板，用的小兵原版15.4镜像，HDMI可以显示，但是显存为7MB，加速显示启用，而且分辨率貌似也不太正常。求问大佬您的方案怎么用?

**Comment by Good0007** [comment]
替换EFI，具体操作看下教程..

**Comment by naughtyGitCat** [comment]
> 替换EFI，具体操作看下教程..

是指小兵的教程吗，我看你的连接里面没有将怎么替换啊

**Comment by Good0007** [comment]
教程都是通用的，重复写没意义，网上很多，可以看小兵博客里的教程
